spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.224.137/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: E:\wechatbookfoodlog
  file: E:\wechatbookfoodlog\sell.log